### ISSUE TITLE
failed to 'import filter_fns'

### ISSUE THREAD

**Issue by sunnycia** [saumya-jetley/cd_Saliency_PDP#1]
Hi, appreciate your work, but I failed to 'import filter_fns' in the _train_net.py_ in the _Loss_layer_ folder. 
Any workaround to suggest? Thanks!

**Comment by sunnycia** [comment]
The implementation of _filter_fns_ and _frcnn_fns_ is missing in this repo.

**Comment by saumya-jetley** [comment]
Hello @sunnycia, thanks for your message. I have noted this and will get back to you asap.

**Comment by saumya-jetley** [comment]
The file sal_helpers.py (uploaded in the latest commit) contains the missing functionalities. It serves as a replacement for filter_fns and frcnn_fns.
